# Generated by Django 4.0.3 on 2022-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=15, null=True, verbose_name='marca')),
                ('modello', models.CharField(blank=True, max_length=15, null=True, verbose_name='modello')),
                ('prezzo', models.IntegerField()),
                ('km', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('dettagli', models.CharField(blank=True, max_length=255, null=True)),
                ('immagine', models.ImageField(upload_to='media')),
            ],
        ),
    ]
